"""esquema inicial

Revision ID: 3d3e142ea09b
Revises: 
Create Date: 2026-09-03 02:46:08.277567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d3e142ea09b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('servidor', 'aplicacion', 'base_datos', 'red', 'endpoint', 'sistema_web_publico', name='asset_type'), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('criticality', sa.Enum('baja', 'media', 'alta', 'critica', name='asset_criticality'), nullable=False),
    sa.Column('status', sa.Enum('activo', 'mantenimiento', 'dado_de_baja', name='asset_status'), nullable=False),
    sa.Column('owner', sa.String(length=150), nullable=False),
    sa.Column('location', sa.Enum('fisico', 'nube', 'on_prem', name='asset_location'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nist_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('function', sa.Enum('identify', 'protect', 'detect', 'respond', 'recover', name='nist_function'), nullable=False),
    sa.Column('question_code', sa.String(length=20), nullable=False),
    sa.Column('question_text', sa.String(length=500), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin_ti', 'analista_riesgo', 'directivo', name='user_role'), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('demo_business_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vulnerabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_band', sa.Enum('bajo', 'medio', 'alto', 'critico', name='risk_band'), nullable=False),
    sa.Column('status', sa.Enum('abierta', 'mitigada', name='vulnerability_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('impact BETWEEN 1 AND 5', name='ck_vuln_impact_range'),
    sa.CheckConstraint('probability BETWEEN 1 AND 5', name='ck_vuln_probability_range'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vulnerability_id', sa.UUID(), nullable=True),
    sa.Column('nist_function', sa.Enum('identify', 'protect', 'detect', 'respond', 'recover', name='nist_function'), nullable=True),
    sa.Column('source', sa.Enum('regla', 'llm', name='recommendation_source'), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    op.drop_table('vulnerabilities')
    op.drop_table('demo_business_metrics')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('nist_assessments')
    op.drop_table('assets')
    # ### end Alembic commands ###
