"""constraint rango score nist

Revision ID: a1e1c8efb61c
Revises: 3d3e142ea09b
Create Date: 2026-09-03 03:15:13.250437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1e1c8efb61c'
down_revision: Union[str, None] = '3d3e142ea09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
